### ISSUE TITLE
[BUG] WallpaperPicker : InfinityWallpaper FC

### ISSUE THREAD

**Issue by ananjaser1211** [ananjaser1211/FloydQ_Reports#1]
**Describe the bug**
- FC when switching between InfinityWallpaper styles

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7 EDGE]
 - Model: [e.g. G935F]

**Additional context**

```
2020-04-19 23:31:23.849 10983-10983/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.systemui:WallpaperPreview, PID: 10983
    java.lang.SecurityException: Access denied to process: 10983, must have permission android.permission.SET_WALLPAPER_COMPONENT
        at android.os.Parcel.createException(Parcel.java:2088)
        at android.os.Parcel.readException(Parcel.java:2056)
        at android.os.Parcel.readException(Parcel.java:2004)
        at android.app.IWallpaperManager$Stub$Proxy.setWallpaperComponentChecked(IWallpaperManager.java:2040)
        at android.app.WallpaperManager.setWallpaperComponent(WallpaperManager.java:3128)
        at android.app.WallpaperManager.setWallpaperComponent(WallpaperManager.java:3104)
        at com.android.systemui.wallpaper.KeyguardWallpaperPreviewActivity.doSetAsWallpaper(KeyguardWallpaperPreviewActivity.java:834)
        at com.android.systemui.wallpaper.KeyguardWallpaperPreviewActivity.access$900(KeyguardWallpaperPreviewActivity.java:102)
        at com.android.systemui.wallpaper.KeyguardWallpaperPreviewActivity$6.onClick(KeyguardWallpaperPreviewActivity.java:500)
        at android.view.View.performClick(View.java:7870)
        at android.widget.TextView.performClick(TextView.java:14952)
        at android.view.View.performClickInternal(View.java:7839)
        at android.view.View.access$3600(View.java:886)
        at android.view.View$PerformClick.run(View.java:29363)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.wallpaper.WallpaperManagerService.checkPermission(Unknown Source:40)
        at com.android.server.wallpaper.WallpaperManagerService.setWallpaperComponent(Unknown Source:28)
        at com.android.server.wallpaper.WallpaperManagerService.setWallpaperComponent(Unknown Source:1)
        at com.android.server.wallpaper.WallpaperManagerService.setWallpaperComponentChecked(Unknown Source:12)
        at android.app.IWallpaperManager$Stub.onTransact(IWallpaperManager.java:998)
```

**Comment by ananjaser1211** [comment]
BUG has been fixed in internal V2 Build.

**Comment by ananjaser1211** [comment]
EDIT : i will keep the issues open till V2 is out, but mark the labels as "fixed"
